### ISSUE TITLE
layer format

### ISSUE THREAD

**Issue by adelin-b** [adelin-b/yawhich-key#15]
The new layer format should be
```yaml
name: layername

# Which window class with it match against
window_class: all

dependencies:
  - command: git
    # will be displayed if the command doesnt exist
    install:
    uninstall:

# Commands to run to add custom variables for example
hooks:
  before_start:
   - layer_specific_variable=$(echo hello world)
  after_start:
  before_end:
  after_end:

map:
  +!-shell:
  # Plugins or additional integration
  +menu:
    submenu+1: echo $layer_specific_variable

    submenu+2:
      command: echo hello
      # The command will stay on the current yawhich-key window once done
      transient: true
      # Need confirmation
      confirm: true

```
